name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      # 3. Instalar dependências
      - name: Install dependencies
        run: yarn install

      # 4. Rodar os testes Cypress
      - name: Run Cypress tests
        run: yarn cypress run
